### ISSUE TITLE
Problem with accents

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GitHubCity#73]
Traceback (most recent call last):
  File "process.py", line 9, in <module>
    ciudad = GitHubCity(idGH, secretGH, city="Albacete", locations=locations,debug=True)

  File "/usr/local/lib/python3.4/dist-packages/githubcity/ghcity.py", line 135, in __init__
    self._addLocationsToURL(self._locations)
  File "/usr/local/lib/python3.4/dist-packages/githubcity/ghcity.py", line 166, in _addLocationsToURL
    self._urlLocations += "+location:" + str(urllib.parse.quote(l))
  File "/usr/lib/python3.4/urllib/parse.py", line 694, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.4/urllib/parse.py", line 719, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by iblancasa** [comment]
The problem is caused by "Hellín"
